Resources:
  DocumentStorageBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'document-qa-bucket-${AWS::AccountId}-${AWS::Region}'
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: 'ExpireOldDocuments'
            Status: Enabled
            ExpirationInDays: 30
      AccessControl: Private
      Tags:
        - Key: Name
          Value: DocumentQAStorage