Resources:
  SageMakerEndpoint:
    Type: AWS::SageMaker::Endpoint
    Properties: 
      EndpointConfigName: !Ref SageMakerEndpointConfig

  SageMakerEndpointConfig:
    Type: AWS::SageMaker::EndpointConfig
    Properties:
      ProductionVariants:
        - VariantName: AllTraffic
          ModelName: !Ref SageMakerModel
          InitialInstanceCount: 1
          InstanceType: ml.m5.large
          InitialVariantWeight: 1.0

  SageMakerModel:
    Type: AWS::SageMaker::Model
    Properties:
      ExecutionRoleArn: !GetAtt SageMakerExecutionRole.Arn
      PrimaryContainer:
        Image: <your-sagemaker-image-uri>
        ModelDataUrl: <your-model-data-s3-uri>

  SageMakerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SageMakerExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource: 
                  - <your-s3-bucket-arn>
                  - <your-s3-bucket-arn>/*